#version 460

#include "boid_comp.h"

layout (local_size_x = 256) in;


void reset_boid(uint index)
{
	uint random_state = romu_mono_init(index);
	vec2 pos;
	vec2 vel;
	switch(PC.kernel_index)
	{
	default:
	case 0:
	{
		pos.x = romu_mono_float(random_state);
		pos.y = romu_mono_float(random_state);
		vel.x = romu_mono_float(random_state);
		vel.y = romu_mono_float(random_state);
	}break;
	case 1:
	{
		float range = 0.5;
		float d;
		do{
			pos.x = romu_mono_float(random_state) * range;
			pos.y = romu_mono_float(random_state) * range;
			d = distance(pos, vec2(0.0));
		}while(d > 0.5 || d < 0.2);

		vel = normalize(pos);
		vel = vec2(-vel.y, vel.x);
	}break;
	}

	vel *= 0.00001;



	Boid b;
	b.velocity = vel;
	b.position = pos;
	writeonly_boids.data[index] = b;
	readonly_boids.data[index] = b;
}

void main()
{
	uint GLOBAL_INVOCATION = gl_GlobalInvocationID.x;
	uint LOCAL_INVOCATION = gl_LocalInvocationID.x;
	uint WORK_GROUP = gl_WorkGroupID.x;
	uint WORK_GROUP_SIZE = gl_WorkGroupSize.x;
	uint WORK_GROUP_COUNT = gl_NumWorkGroups.x;
	uint INVOCATION_COUNT = WORK_GROUP_COUNT * WORK_GROUP_SIZE;

	for(uint i = GLOBAL_INVOCATION; i < PC.boid_count; i += INVOCATION_COUNT)
	{
		reset_boid(i);
	}
}
