#version 460

#include "boid_comp.h"



void reset_boid(uint index)
{
	uint random_state = romu_mono_init(index);
	Boid b;
	b.position.x = romu_mono_float(random_state);
	b.position.y = romu_mono_float(random_state);
	vec2 pos = b.position;
	vec2 vel = normalize(pos);
	vel = vec2(-vel.y, vel.x);
	b.velocity.x = romu_mono_float(random_state);
	b.velocity.y = romu_mono_float(random_state);
	b.velocity = vel;
	writeonly_boids.data[index] = b;
}

void main()
{
	uint GLOBAL_INVOCATION = gl_GlobalInvocationID.x;
	uint LOCAL_INVOCATION = gl_LocalInvocationID.x;
	uint WORK_GROUP = gl_WorkGroupID.x;
	uint WORK_GROUP_SIZE = gl_WorkGroupSize.x;
	uint WORK_GROUP_COUNT = gl_NumWorkGroups.x;
	uint INVOCATION_COUNT = WORK_GROUP_COUNT * WORK_GROUP_SIZE;

	for(uint i = GLOBAL_INVOCATION; i < PC.boid_count; i += INVOCATION_COUNT)
	{
		reset_boid(i);
	}
}
