#version 450 core
#pragma shader_stage(compute)

layout(local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

layout(set = 0, binding = 0, rgba8) uniform image2D target;


void main()
{
	uvec2 tid = gl_GlobalInvocationID.xy;
	uvec2 target_size = imageSize(target);
	if(tid.x < target_size.x && tid.y < target_size.y)
	{
		uvec2 id = tid / 10;
		uint v = id.x + (id.y & 1);
		if((v & 1) == 0)
		{
			vec4 color = vec4(1.0, 0.1, 0.1, 1.0);
			imageStore(target, ivec2(tid), color);
		}
		else
		{
			vec4 color = vec4(0.0, 0.1, 0.1, 1.0);
			imageStore(target, ivec2(tid), color);
		}
	}

}
